### ISSUE TITLE
Delete buffer doesn't work

### ISSUE THREAD

**Issue by Kyren223** [ChuufMaster/buffer-vacuum#1]
If you are above MAX, it only deletes 1 buffer at a time, so if u have 10 buffers with max 6,
the expected behaviour would be to delete 4 oldest buffers to only keep 6. (assuming non of those buffers are unchanged/unpinned)

This is relevant, because even if I have 3 buffers and start opening them, then get to 6, but then leave neovim and open it again (and all the 6 buffers are restored) it then allows me to have 7+ buffers due to it being MAX.

I tried forking and fixing it myself, I wasn't able to figure it out, it has to do with >= expr evaluating to false

**Comment by ChuufMaster** [comment]
I have come across this issue before and I haven't quite figured it out yet, I have figured out why it happens and its because of the way that the session managers restore the buffers. The reason it doesn't work with session managers is because when a session is restored the buffers aren't actually loaded until you enter them, essentially all of the buffers are bookmarked by the session but aren't opened I am still trying to figure out a way to make it work but the biggest problem with it is that session managers store and restore sessions in different ways and I don't know how to make a universal solution.

Which session manager do you use and I will have a look at how it store the buffers.

**Comment by Kyren223** [comment]
I use auto-session (the one with 1.1k-ish stars)
I think most session managers (that don't use a custom solution) rely on either the built in session tools (mksession) or shada

**Comment by ChuufMaster** [comment]
Thanks I will have a look into it

**Comment by Kyren223** [comment]
Any updates?

**Comment by ChuufMaster** [comment]
Hi yes sorry I currently in the final year of my undergrad compsci degree so the I haven’t had much time to work on this plugin but I’m still planning on fixing it up and I’ve learnt a lot more about neocon and its capabilities since I originally wrote this so I’m definitely Going to attempt to make it work with sessions and see if there aren’t other cool things I can do with it

**Comment by ChuufMaster** [comment]
@Kyren223 I have finally gotten round to fixing the session integration

**Comment by Kyren223** [comment]
Thanks!
Also cleaning up once when it first loads can be nice, not a big deal as opening a buffer that isn't in the buffer list will trigger it.

**Comment by ChuufMaster** [comment]
Not a bad idea, I will look into it.
